services:
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - microservices-net

volumes:
  keycloak-data:

networks:
  microservices-net:
