export enum TypePhase {
  INITIATION = 'INITIATION',
  PLANIFICATION = 'PLANIFICATION',
  CONCEPTION = 'CONCEPTION',
  DEVELOPPEMENT = 'DEVELOPPEMENT',
  TEST = 'TEST',
  DEPLOIEMENT = 'DEPLOIEMENT',
  CLOTURE = 'CLOTURE',
}
